#!/bin/bash
# Tested on uv100.awi.de (SGI UV 100, details:
#                         http://www.sgi.com/products/servers/uv/specs.html)
# a) For more speed, provided your data size does not exceed 2GB you can
#    remove -fPIC which carries a performance penalty of 2-6%.
# b) You can replace -fPIC with '-mcmodel=medium -shared-intel' which may
#    perform faster than -fPIC and still support data sizes over 2GB per
#    process but all the libraries you link to must be compiled with
#    -fPIC or -mcmodel=medium
# c) flags adjusted for ifort 12.1.0

FC=mpifort
F90C=mpifort
CC=mpicc
# requires that all static libraries are available:
#LINK='ifort -static'
LINK='mpifort'
# for adjoint runs the default makedepend often cannot handle enough files
#MAKEDEPEND=tools_xmakedepend

DEFINES='-DWORDLENGTH=4'
CPP='cpp -traditional -P'
F90FIXEDFORMAT='-fixed -Tf'
EXTENDED_SRC_FLAG='-132'
#OMPFLAG='-openmp'

NOOPTFILES=''

# MCMODEL='-fPIC'
# for large memory requirements uncomment this line
MCMODEL='-mcmodel=medium'

FFLAGS="$FFLAGS $MCMODEL -assume byterecl"
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

if test "x$IEEE" = x ; then     #- with optimisation:
    FOPTIM='-O3 -fpe0'
# does not work when -static does not work
#    FOPTIM='-fast -align'
# instead you can use
#    FOPTIM='-O3 -ipo -align'
else
  if test "x$DEVEL" = x ; then  #- no optimisation + IEEE :
    FOPTIM='-O0 -noalign -fp-model precise'
   # -fltconsistency
  else                          #- development/check options:
    FOPTIM='-O0 -noalign -fp-model precise'
    FOPTIM="$FOPTIM -g -check all -fpe0 -traceback -ftrapuv -fp-model except -warn all"
  fi
fi

F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM
CFLAGS="-O0 $MCMODEL"

INCLUDEDIRS=''
INCLUDES=''
LIBS=''



if [ -n "$MPI_INC_DIR" -a "x$MPI" = xtrue ] ; then
    LIBS="$LIBS -lmpi"
    INCLUDES="$INCLUDES -I$MPI_INC_DIR"
    INCLUDEDIRS="$INCLUDEDIRS $MPI_INC_DIR"
    #- used for parallel (MPI) DIVA
    MPIINCLUDEDIR="$MPI_INC_DIR"
   #MPI_HEADER_FILES='mpif.h mpiof.h'
fi
